### ISSUE TITLE
High Priority/Commonly reported bugs for v1.6

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#1556]
The following critical bugs should be investigated and fixed ASAP:
 - [x] Snap possibly broken in Jester Ep. 4 (https://github.com/TerryCavanagh/diceydungeons.com/issues/1552)
 - [x] Cutscene crash bug (https://github.com/TerryCavanagh/diceydungeons.com/issues/1550)
 - [x] Crash bug on resuming a continue save as Inventor that seems new to v1.6 (https://github.com/TerryCavanagh/diceydungeons.com/issues/1544)
 - [x] Double inventor gadgets not working correctly? Very very serious if it applies to more than just the initial gadgets! (https://github.com/TerryCavanagh/diceydungeons.com/issues/1516)
 - [x] Jester's Booster Pack substitutions are broken (https://github.com/TerryCavanagh/diceydungeons.com/issues/1501)
 - [x] Softlock when fighting an Alchemist that turns into a bear if you shock them on the same turn (https://github.com/TerryCavanagh/diceydungeons.com/issues/1469, https://github.com/TerryCavanagh/diceydungeons.com/issues/1351, https://github.com/TerryCavanagh/diceydungeons.com/issues/1428, https://github.com/TerryCavanagh/diceydungeons.com/issues/1406)

And the following bugs get reported a lot and should be a priority for the next build:
 - [x] Inventor Silenced slots are difficult to connect dice to, and require a lot of juggling around (https://github.com/TerryCavanagh/diceydungeons.com/issues/1168)
 - [x] Yolanda doesn't say anything if you buy everything in her shop (https://github.com/TerryCavanagh/diceydungeons.com/issues/1541)
 - [x] Missing level up reward in Expect the Unexpected (https://github.com/TerryCavanagh/diceydungeons.com/issues/1518)
 - [x] Skeleton's sword gets swapped for weird stuff due to substitution rules (https://github.com/TerryCavanagh/diceydungeons.com/issues/1555)

**Comment by ncrecc** [comment]
Also reported frequently is #1514 (transforming into bear doesn't wipe backpack anymore), some even think it's a feature

**Comment by TerryCavanagh** [comment]
Yay, I've finally fixed everything on this list! That's great 🎉
