### ISSUE TITLE
Various issues with Copycat

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#2013]
- [ ] Copycat doesn't act correctly after using Bump (https://github.com/TerryCavanagh/diceydungeons.com/issues/1540)
 - [ ] Doesn't seem to take substitutions into account (https://github.com/TerryCavanagh/diceydungeons.com/issues/1574)
 - [ ] Copycat can trigger the Precious Egg achievement (https://github.com/TerryCavanagh/diceydungeons.com/issues/1602)
 - [ ] Berlin Key can cause Copycat to softlock (https://github.com/TerryCavanagh/diceydungeons.com/issues/1799)
 - [ ] When facing Jester, size 2 cards can become size 1, which looks very weird (this is an easier fix than it sounds like) (https://github.com/TerryCavanagh/diceydungeons.com/issues/2003)

**Comment by TerryCavanagh** [comment]
An older collection: https://github.com/TerryCavanagh/diceydungeons.com/issues/895
