### ISSUE TITLE
Various issues with status effect and equipment edge cases

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#2014]
- [ ] Taking damage from Poison and burning dice also makes you take damage from your Thorns (https://github.com/TerryCavanagh/diceydungeons.com/issues/1455, https://github.com/TerryCavanagh/diceydungeons.com/issues/1797)
 - [ ] The game's weird implementation of Enemy blind means that Keymaster can use a single dice to unlock several keyblades (https://github.com/TerryCavanagh/diceydungeons.com/issues/1512, https://github.com/TerryCavanagh/diceydungeons.com/issues/1596)
 - [ ] Dice status effects can be a little weird when you gain more dice on your turn with e.g. lockpick or cauldron (https://github.com/TerryCavanagh/diceydungeons.com/issues/1784)
 - [ ] Mood Change should destroy other weather effects (https://github.com/TerryCavanagh/diceydungeons.com/issues/1447)
 - [ ] You can use multislot equipment to completely disable Lock?ed dice (https://github.com/TerryCavanagh/diceydungeons.com/issues/1956)
 - [ ] Counter X status effects are a little buggy: they don't really work in some important cases like e.g. freezing a dice and countering 1s (https://github.com/TerryCavanagh/diceydungeons.com/issues/1800, https://github.com/TerryCavanagh/diceydungeons.com/issues/1905, https://github.com/TerryCavanagh/diceydungeons.com/issues/1906, https://github.com/TerryCavanagh/diceydungeons.com/issues/1954)
 - [ ] Enemies with multiple countdowns only really consider their first countdown item, which can cause a couple of weird issues, some of which are fairly gamebreaking (https://github.com/TerryCavanagh/diceydungeons.com/issues/1755)

**Comment by Matz-42** [comment]
Mind taking a look at #1654 as a potential fix for #1755 ?
