### ISSUE TITLE
Various issues with the Weaken status effect

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#2015]
- [x] Weaken removes the charge on Lightning Rod (https://github.com/TerryCavanagh/diceydungeons.com/issues/1460)
 - [x] Run Away+ is an automatic threequartercountdown, but Run Away has no _weakened version (https://github.com/TerryCavanagh/diceydungeons.com/issues/1491)
 - [x] Once per battle equipment can be used again if weakened (https://github.com/TerryCavanagh/diceydungeons.com/issues/424, https://github.com/TerryCavanagh/diceydungeons.com/issues/1941)

**Comment by TerryCavanagh** [comment]
Fixed all of these! Great! Closing.
