### ISSUE TITLE
Various issues with the Finale episode

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#2016]
- [ ] Burn doesn't work correctly on Robot (https://github.com/TerryCavanagh/diceydungeons.com/issues/1462)
 - [ ] It's possible to skip Wheel of Fortune if you Lock and Shock Lady Luck on the same turn (https://github.com/TerryCavanagh/diceydungeons.com/issues/1587, https://github.com/TerryCavanagh/diceydungeons.com/issues/1230)
 - [ ] If you're commanded not to use a certain number, you can still use a dice with that number on countdowns (https://github.com/TerryCavanagh/diceydungeons.com/issues/1764)
 - [ ] Small bug in the final cutscene if you don't using the player character for the final blow (https://github.com/TerryCavanagh/diceydungeons.com/issues/1796)
