### ISSUE TITLE
Various issues with Jester

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#2017]
There are lots and lots of small issues with Jester that aren't really that important, but should probably be fixed up for v1.10.

 - [ ] Call for Backup cards should not trigger curse (https://github.com/TerryCavanagh/diceydungeons.com/issues/1470, https://github.com/TerryCavanagh/diceydungeons.com/issues/1451)
 - [ ] Potential issue with Kapow counter needs to be checked for problems (https://github.com/TerryCavanagh/diceydungeons.com/issues/1495, https://github.com/TerryCavanagh/diceydungeons.com/issues/1568)
 - [ ] Reported crash bug (https://github.com/TerryCavanagh/diceydungeons.com/issues/1553)
 - [ ] Some messy interactions from stealing giveequipment() related stuff in Losers, Weepers (https://github.com/TerryCavanagh/diceydungeons.com/issues/1594, https://github.com/TerryCavanagh/diceydungeons.com/issues/1595)
 - [ ] Jester trades with Val will use the regular upgrades instead of deckupgrades (https://github.com/TerryCavanagh/diceydungeons.com/issues/1607)
 - [ ] Snapping any item with FREEX slots gives you extra dice (https://github.com/TerryCavanagh/diceydungeons.com/issues/1735)
 - [ ] Fury stacking is buggy, especially with Snap (https://github.com/TerryCavanagh/diceydungeons.com/issues/1766)
 - [ ] Finale text above cards in chests and in shops should only appear if you're actually playing as Jester (https://github.com/TerryCavanagh/diceydungeons.com/issues/1841)
 - [ ] You should be able to snap/discard matching cards regardless of whether they're normal, upgraded or downgraded (https://github.com/TerryCavanagh/diceydungeons.com/issues/1886)
 - [ ] Discard/Snap don't work for four cards at once (https://github.com/TerryCavanagh/diceydungeons.com/issues/1890)

**Comment by Matz-42** [comment]
A little thing that could be interesting and would go along #1841 is letting cards with the same visual name but not the same internal name be snapped/discarded together.
So MyItem@1 and MyItem@2 could be snapped together.

This probably wouldn't happen in vanilla, but for modded I think it's fair to assume that it's the modder's intention to have equipments with the same name technically be the same equipment, just different versions.

**Comment by ncrecc** [comment]
#1594 and #1595 can be reproduced with just the Call for Backup Thief card, being in Losers Weepers isn't required
