### ISSUE TITLE
Various issues with localisations

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#2018]
- [x] Some issues with Traditional Chinese (https://github.com/TerryCavanagh/diceydungeons.com/issues/1530)
 - [x] More issues with Traditional Chinese (https://github.com/TerryCavanagh/diceydungeons.com/issues/1913)
 - [x] Multiple suggestions for French (https://github.com/TerryCavanagh/diceydungeons.com/labels/French%20Localisation%20Feedback)
 - [x] A new system is needed to deal with long names in bestiary screen (https://github.com/TerryCavanagh/diceydungeons.com/issues/1774)

**Comment by TerryCavanagh** [comment]
Ok! All of these are now addressed.
