### ISSUE TITLE
Most urgent recurring gameplay issues and requests

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#859]
A lot of people discovered Dicey Dungeons in January, yikes!

The following issues come up *a lot*. I know I have issues about them already, but I'm going to collect them all here to have them in one place, and make sure they don't get overlooked. These issues are *the most important* ones in Dicey Dungeons, and should be considered a priority.

**Bugs**
 - [x] The Equipment screen has a number of glitches that are long overdue a fix. (https://github.com/TerryCavanagh/diceydungeons.com/issues/797, https://github.com/TerryCavanagh/diceydungeons.com/issues/700, https://github.com/TerryCavanagh/diceydungeons.com/issues/184, https://github.com/TerryCavanagh/diceydungeons.com/issues/49, https://github.com/TerryCavanagh/diceydungeons.com/issues/16)
 - [x] Drinking the bear potion crashes the game (https://github.com/TerryCavanagh/diceydungeons.com/issues/793, https://github.com/TerryCavanagh/diceydungeons.com/issues/857).
 - [x] The enemy moves preview button causes a number of glitches, including lost dice and missing actions. (https://github.com/TerryCavanagh/diceydungeons.com/issues/846, https://github.com/TerryCavanagh/diceydungeons.com/issues/817, https://github.com/TerryCavanagh/diceydungeons.com/issues/800, https://github.com/TerryCavanagh/diceydungeons.com/issues/751, https://github.com/TerryCavanagh/diceydungeons.com/issues/749, https://github.com/TerryCavanagh/diceydungeons.com/issues/712, https://github.com/TerryCavanagh/diceydungeons.com/issues/675)
 - [x] Crowbar and countdowns in general have some weird buggy behaviour (https://github.com/TerryCavanagh/diceydungeons.com/issues/828, https://github.com/TerryCavanagh/diceydungeons.com/issues/549, https://github.com/TerryCavanagh/diceydungeons.com/issues/494, https://github.com/TerryCavanagh/diceydungeons.com/issues/459, https://github.com/TerryCavanagh/diceydungeons.com/issues/447, https://github.com/TerryCavanagh/diceydungeons.com/issues/394, https://github.com/TerryCavanagh/diceydungeons.com/issues/210)
 - [x] Grabbing dice as they're moving in a tween breaks their position (https://github.com/TerryCavanagh/diceydungeons.com/issues/807)
 - [x] Using Inventor Steal can soft-lock the game. (https://github.com/TerryCavanagh/diceydungeons.com/issues/732, https://github.com/TerryCavanagh/diceydungeons.com/issues/629)
 - [x] It's possible for dice to overlap, and this often happens when using the Robot's Autoroll limit break (https://github.com/TerryCavanagh/diceydungeons.com/issues/405, https://github.com/TerryCavanagh/diceydungeons.com/issues/206)

**Design issues**
 - [x] The game needs a short, snappy tutorial. (https://github.com/TerryCavanagh/diceydungeons.com/issues/441)
 - [x] Lots of new players are finding the game too easy. (https://github.com/TerryCavanagh/diceydungeons.com/issues/845)
 - [x] Level up pacing feels slightly off near the end (https://github.com/TerryCavanagh/diceydungeons.com/issues/847). Related: Lots of players request some kind of endless mode where they can try out their build against a tougher challenge.
 - [x] Level up rewards for all classes need revising (https://github.com/TerryCavanagh/diceydungeons.com/issues/869, https://github.com/TerryCavanagh/diceydungeons.com/issues/809, https://github.com/TerryCavanagh/diceydungeons.com/issues/713, https://github.com/TerryCavanagh/diceydungeons.com/issues/198)
 - [x] An enemy design audit is overdue. In particular, these enemies feel off: Wolf Puppy (https://github.com/TerryCavanagh/diceydungeons.com/issues/802), Baby Squid (https://github.com/TerryCavanagh/diceydungeons.com/issues/790), Wizard (https://github.com/TerryCavanagh/diceydungeons.com/issues/801), Kraken (https://github.com/TerryCavanagh/diceydungeons.com/issues/833), Paper Knight (https://github.com/TerryCavanagh/diceydungeons.com/issues/724), Wicker Man (https://github.com/TerryCavanagh/diceydungeons.com/issues/678), Dragon (https://github.com/TerryCavanagh/diceydungeons.com/issues/519).
 - [x] Some level up rewards and items don't make any sense for the various quests they appear in (especially Robot's Dice for a Price)
 - [x] There are too many unnecessary confirmation steps when collecting items - picking up items from a chest shouldn't offer to ignore it (https://github.com/TerryCavanagh/diceydungeons.com/issues/387), and you shouldn't get a separate confirmation after you buy equipment from a shop (https://github.com/TerryCavanagh/diceydungeons.com/issues/733, https://github.com/TerryCavanagh/diceydungeons.com/issues/166).
 - [x] Inventor needs a couple of tweaks which should massively improve it: starting with scrap metal makes them seem more confusing than they are, because it introduces a concept before you see it (https://github.com/TerryCavanagh/diceydungeons.com/issues/714), and you should be able to preview the gadgets that you get from equipment somehow (https://github.com/TerryCavanagh/diceydungeons.com/issues/856, https://github.com/TerryCavanagh/diceydungeons.com/issues/237).
 - [x] Witch should be able to rearrange her spellbook. (https://github.com/TerryCavanagh/diceydungeons.com/issues/491)
 - [x] You can't cancel a spell cast right now. (https://github.com/TerryCavanagh/diceydungeons.com/issues/246)
 - [x] New players often want to sell, or at least dump unwanted equipment (https://github.com/TerryCavanagh/diceydungeons.com/issues/217)

**UI and communication issues**
  - [x] Replace the current mini-dice icon with one that doesn't indicate any particular number. (https://github.com/TerryCavanagh/diceydungeons.com/issues/227, https://github.com/TerryCavanagh/diceydungeons.com/issues/813)
  - [x] The settings menu needs a proper redesign. (https://github.com/TerryCavanagh/diceydungeons.com/issues/699, https://github.com/TerryCavanagh/diceydungeons.com/issues/599)
  - [x] Status effects shouldn't disappear when "applied" - instead they should stay in place, so that players can mouse over them to see what happened. (https://github.com/TerryCavanagh/diceydungeons.com/issues/814)
 - [x] Make the connection between levels and stars clearer. (https://github.com/TerryCavanagh/diceydungeons.com/issues/723)
 - [x] Communicate that Poison pierces shields somewhere.
 - [x] Explain in game what is meant by "Strength" and "Weakness"
 - [x] Witch spells need to be previewable. (https://github.com/TerryCavanagh/diceydungeons.com/issues/855, https://github.com/TerryCavanagh/diceydungeons.com/issues/617)
 - [x] Flee counter is broken. New players aren't even aware that fleeing is an option. (https://github.com/TerryCavanagh/diceydungeons.com/issues/748, https://github.com/TerryCavanagh/diceydungeons.com/issues/533)
 - [x] Make it clearer that the Thief is "stealing" enemy equipment every turn. (https://github.com/TerryCavanagh/diceydungeons.com/issues/297)

**Comment by ncrecc** [comment]
Dumping equipment would be rather useful in Finders Keepers. Right now, vampire is unwinnable if you completely completely filling your backpack and equipment bar before taking Wooden Stake.

**Comment by ncrecc** [comment]
I think explaining what "strength" and "weakness" mean would be as simple as rewriting the strong/weak to lines, e.g.: "Enemy takes double damage from [element] attacks" and "Enemy takes half as much damage from [element] attacks".
